import { Exercise, MuscleGroup, EquipmentCategory, ExerciseCategory, DifficultyLevel } from '../types';

export const defaultExercises: Exercise[] = [
  {
    id: 'barbell_squat',
    name: '杠铃深蹲',
    nameEn: 'Barbell Squat',
    category: 'compound',
    muscleGroups: ['quads', 'glutes', 'hamstrings', 'core'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    instructions: ['双脚与肩同宽', '杠铃置于上背', '下蹲至大腿平行地面', '膝盖与脚尖同向'],
    replacementIds: ['goblet_squat', 'leg_press', 'smith_squat'],
    isCustom: false,
  },
  {
    id: 'goblet_squat',
    name: '高脚杯深蹲',
    nameEn: 'Goblet Squat',
    category: 'compound',
    muscleGroups: ['quads', 'glutes', 'core'],
    equipment: ['dumbbell', 'kettlebell'],
    difficulty: 'beginner',
    instructions: ['双手持哑铃/壶铃于胸前', '保持躯干直立', '下蹲至肘部触膝', '站起时收紧臀部'],
    replacementIds: ['barbell_squat', 'bodyweight_squat'],
    isCustom: false,
  },
  {
    id: 'bodyweight_squat',
    name: '自重深蹲',
    nameEn: 'Bodyweight Squat',
    category: 'compound',
    muscleGroups: ['quads', 'glutes'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: ['双脚与肩同宽', '双臂前伸保持平衡', '下蹲至大腿平行地面', '站起时收紧臀部'],
    replacementIds: ['goblet_squat', 'barbell_squat'],
    isCustom: false,
  },
  {
    id: 'leg_press',
    name: '腿举',
    nameEn: 'Leg Press',
    category: 'compound',
    muscleGroups: ['quads', 'glutes', 'hamstrings'],
    equipment: ['machine'],
    difficulty: 'beginner',
    instructions: ['背部紧贴靠垫', '双脚与肩同宽踩踏板', '缓慢下放至90度', '不要完全锁死膝盖'],
    replacementIds: ['barbell_squat', 'smith_squat'],
    isCustom: false,
  },
  {
    id: 'smith_squat',
    name: '史密斯深蹲',
    nameEn: 'Smith Machine Squat',
    category: 'compound',
    muscleGroups: ['quads', 'glutes'],
    equipment: ['smith_machine'],
    difficulty: 'beginner',
    instructions: ['将杠铃置于上背', '双脚前移至合适位置', '下蹲至大腿平行', '沿固定轨迹运动'],
    replacementIds: ['barbell_squat', 'leg_press'],
    isCustom: false,
  },
  {
    id: 'bench_press',
    name: '卧推',
    nameEn: 'Bench Press',
    category: 'compound',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipment: ['barbell', 'bench'],
    difficulty: 'intermediate',
    instructions: ['平躺在卧推凳上', '握距略宽于肩', '下放至胸部', '推起至手臂伸直不锁死'],
    replacementIds: ['dumbbell_bench_press', 'push_up', 'machine_chest_press'],
    isCustom: false,
  },
  {
    id: 'dumbbell_bench_press',
    name: '哑铃卧推',
    nameEn: 'Dumbbell Bench Press',
    category: 'compound',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipment: ['dumbbell', 'bench'],
    difficulty: 'beginner',
    instructions: ['双手各持一个哑铃', '平躺在卧推凳上', '下放至胸部两侧', '推起时感受胸肌收缩'],
    replacementIds: ['bench_press', 'push_up'],
    isCustom: false,
  },
  {
    id: 'push_up',
    name: '俯卧撑',
    nameEn: 'Push-Up',
    category: 'compound',
    muscleGroups: ['chest', 'triceps', 'shoulders', 'core'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: ['双手与肩同宽', '身体保持一条直线', '下放至胸部接近地面', '推起至手臂伸直'],
    replacementIds: ['bench_press', 'dumbbell_bench_press'],
    isCustom: false,
  },
  {
    id: 'machine_chest_press',
    name: '器械推胸',
    nameEn: 'Machine Chest Press',
    category: 'compound',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipment: ['machine'],
    difficulty: 'beginner',
    instructions: ['调整座椅高度', '握住把手', '向前推出', '缓慢回到起始位'],
    replacementIds: ['bench_press', 'dumbbell_bench_press'],
    isCustom: false,
  },
  {
    id: 'deadlift',
    name: '硬拉',
    nameEn: 'Deadlift',
    category: 'compound',
    muscleGroups: ['back', 'hamstrings', 'glutes', 'traps', 'core'],
    equipment: ['barbell'],
    difficulty: 'advanced',
    instructions: ['双脚与髋同宽', '握距在膝盖外侧', '背部保持平直', '腿部发力拉起杠铃'],
    replacementIds: ['romanian_deadlift', 'kettlebell_swing'],
    isCustom: false,
  },
  {
    id: 'romanian_deadlift',
    name: '罗马尼亚硬拉',
    nameEn: 'Romanian Deadlift',
    category: 'compound',
    muscleGroups: ['hamstrings', 'glutes', 'back'],
    equipment: ['barbell', 'dumbbell'],
    difficulty: 'intermediate',
    instructions: ['微屈膝固定', '髋部后移下放杠铃', '感受腘绳肌拉伸', '臀部发力回到起始位'],
    replacementIds: ['deadlift', 'kettlebell_swing'],
    isCustom: false,
  },
  {
    id: 'kettlebell_swing',
    name: '壶铃摆荡',
    nameEn: 'Kettlebell Swing',
    category: 'compound',
    muscleGroups: ['hamstrings', 'glutes', 'core'],
    equipment: ['kettlebell'],
    difficulty: 'intermediate',
    instructions: ['双手持壶铃', '髋部后摆', '利用髋部爆发力前摆', '手臂自然随动'],
    replacementIds: ['romanian_deadlift', 'deadlift'],
    isCustom: false,
  },
  {
    id: 'pull_up',
    name: '引体向上',
    nameEn: 'Pull-Up',
    category: 'compound',
    muscleGroups: ['back', 'biceps', 'forearms'],
    equipment: ['pull_up_bar'],
    difficulty: 'intermediate',
    instructions: ['双手宽握横杆', '身体悬垂', '拉起至下巴过杆', '缓慢下放至手臂伸直'],
    replacementIds: ['lat_pulldown', 'inverted_row'],
    isCustom: false,
  },
  {
    id: 'lat_pulldown',
    name: '高位下拉',
    nameEn: 'Lat Pulldown',
    category: 'compound',
    muscleGroups: ['back', 'biceps'],
    equipment: ['cable'],
    difficulty: 'beginner',
    instructions: ['宽握拉杆', '下拉至锁骨位置', '感受背阔肌收缩', '缓慢回放'],
    replacementIds: ['pull_up', 'inverted_row'],
    isCustom: false,
  },
  {
    id: 'inverted_row',
    name: '反向划船',
    nameEn: 'Inverted Row',
    category: 'compound',
    muscleGroups: ['back', 'biceps'],
    equipment: ['barbell', 'bench'],
    difficulty: 'beginner',
    instructions: ['双手握住低横杆', '身体挺直', '拉起胸部至横杆', '缓慢下放'],
    replacementIds: ['pull_up', 'lat_pulldown'],
    isCustom: false,
  },
  {
    id: 'barbell_row',
    name: '杠铃划船',
    nameEn: 'Barbell Row',
    category: 'compound',
    muscleGroups: ['back', 'biceps', 'traps'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    instructions: ['俯身约45度', '握距与肩同宽', '拉起至腹部', '感受背部收缩'],
    replacementIds: ['dumbbell_row', 'cable_row'],
    isCustom: false,
  },
  {
    id: 'dumbbell_row',
    name: '哑铃划船',
    nameEn: 'Dumbbell Row',
    category: 'compound',
    muscleGroups: ['back', 'biceps'],
    equipment: ['dumbbell', 'bench'],
    difficulty: 'beginner',
    instructions: ['单膝跪在凳上', '对侧手持哑铃', '拉至髋部', '感受背阔肌发力'],
    replacementIds: ['barbell_row', 'cable_row'],
    isCustom: false,
  },
  {
    id: 'cable_row',
    name: '绳索划船',
    nameEn: 'Cable Row',
    category: 'compound',
    muscleGroups: ['back', 'biceps'],
    equipment: ['cable'],
    difficulty: 'beginner',
    instructions: ['坐于器械上', '双手握住把手', '拉至腹部', '感受背部收缩'],
    replacementIds: ['barbell_row', 'dumbbell_row'],
    isCustom: false,
  },
  {
    id: 'overhead_press',
    name: '杠铃推举',
    nameEn: 'Overhead Press',
    category: 'compound',
    muscleGroups: ['shoulders', 'triceps', 'core'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    instructions: ['杠铃置于锁骨前', '双脚与肩同宽', '推举至头顶', '不要过度后仰'],
    replacementIds: ['dumbbell_shoulder_press', 'machine_shoulder_press'],
    isCustom: false,
  },
  {
    id: 'dumbbell_shoulder_press',
    name: '哑铃推举',
    nameEn: 'Dumbbell Shoulder Press',
    category: 'compound',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: ['dumbbell', 'bench'],
    difficulty: 'beginner',
    instructions: ['双手各持哑铃于肩两侧', '推举至头顶', '下放至肩部', '保持核心收紧'],
    replacementIds: ['overhead_press', 'machine_shoulder_press'],
    isCustom: false,
  },
  {
    id: 'machine_shoulder_press',
    name: '器械推举',
    nameEn: 'Machine Shoulder Press',
    category: 'compound',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: ['machine'],
    difficulty: 'beginner',
    instructions: ['调整座椅', '握住把手', '向上推起', '缓慢回到起始位'],
    replacementIds: ['overhead_press', 'dumbbell_shoulder_press'],
    isCustom: false,
  },
  {
    id: 'bicep_curl',
    name: '杠铃弯举',
    nameEn: 'Barbell Curl',
    category: 'isolation',
    muscleGroups: ['biceps', 'forearms'],
    equipment: ['barbell'],
    difficulty: 'beginner',
    instructions: ['双手与肩同宽握杠铃', '上臂固定不动', '弯举至肩部', '缓慢下放'],
    replacementIds: ['dumbbell_curl', 'cable_curl'],
    isCustom: false,
  },
  {
    id: 'dumbbell_curl',
    name: '哑铃弯举',
    nameEn: 'Dumbbell Curl',
    category: 'isolation',
    muscleGroups: ['biceps'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    instructions: ['双手各持一个哑铃', '交替弯举', '上臂固定', '感受二头肌收缩'],
    replacementIds: ['bicep_curl', 'cable_curl'],
    isCustom: false,
  },
  {
    id: 'cable_curl',
    name: '绳索弯举',
    nameEn: 'Cable Curl',
    category: 'isolation',
    muscleGroups: ['biceps'],
    equipment: ['cable'],
    difficulty: 'beginner',
    instructions: ['使用低位滑轮', '握住把手', '弯举至肩部', '保持持续张力'],
    replacementIds: ['bicep_curl', 'dumbbell_curl'],
    isCustom: false,
  },
  {
    id: 'tricep_pushdown',
    name: '三头下压',
    nameEn: 'Tricep Pushdown',
    category: 'isolation',
    muscleGroups: ['triceps'],
    equipment: ['cable'],
    difficulty: 'beginner',
    instructions: ['使用高位滑轮', '握住绳索把手', '下压至手臂伸直', '上臂保持不动'],
    replacementIds: ['skull_crusher', 'dumbbell_tricep_extension'],
    isCustom: false,
  },
  {
    id: 'skull_crusher',
    name: '仰卧臂屈伸',
    nameEn: 'Skull Crusher',
    category: 'isolation',
    muscleGroups: ['triceps'],
    equipment: ['barbell', 'bench'],
    difficulty: 'intermediate',
    instructions: ['平躺在凳上', '握住杠铃于额头上方', '屈肘下放至额头', '伸直手臂'],
    replacementIds: ['tricep_pushdown', 'dumbbell_tricep_extension'],
    isCustom: false,
  },
  {
    id: 'dumbbell_tricep_extension',
    name: '哑铃颈后臂屈伸',
    nameEn: 'Dumbbell Tricep Extension',
    category: 'isolation',
    muscleGroups: ['triceps'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    instructions: ['双手持哑铃于头后', '伸直手臂举过头顶', '上臂保持不动', '缓慢下放'],
    replacementIds: ['tricep_pushdown', 'skull_crusher'],
    isCustom: false,
  },
  {
    id: 'plank',
    name: '平板支撑',
    nameEn: 'Plank',
    category: 'isolation',
    muscleGroups: ['core'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: ['前臂撑地', '身体保持一条直线', '收紧腹部', '保持呼吸'],
    replacementIds: ['dead_bug', 'bird_dog'],
    isCustom: false,
  },
  {
    id: 'dead_bug',
    name: '死虫式',
    nameEn: 'Dead Bug',
    category: 'isolation',
    muscleGroups: ['core'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: ['仰卧屈膝屈髋90度', '对侧手脚同时伸展', '保持腰部贴地', '交替进行'],
    replacementIds: ['plank', 'bird_dog'],
    isCustom: false,
  },
  {
    id: 'bird_dog',
    name: '鸟狗式',
    nameEn: 'Bird Dog',
    category: 'isolation',
    muscleGroups: ['core', 'back'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: ['四点支撑', '对侧手脚同时伸展', '保持躯干稳定', '交替进行'],
    replacementIds: ['plank', 'dead_bug'],
    isCustom: false,
  },
  {
    id: 'lunge',
    name: '弓步蹲',
    nameEn: 'Lunge',
    category: 'compound',
    muscleGroups: ['quads', 'glutes', 'hamstrings'],
    equipment: ['none', 'dumbbell'],
    difficulty: 'beginner',
    instructions: ['一脚向前迈步', '下蹲至双膝约90度', '前膝不超过脚尖', '推回起始位'],
    replacementIds: ['bulgarian_split_squat', 'goblet_squat'],
    isCustom: false,
  },
  {
    id: 'bulgarian_split_squat',
    name: '保加利亚分腿蹲',
    nameEn: 'Bulgarian Split Squat',
    category: 'compound',
    muscleGroups: ['quads', 'glutes'],
    equipment: ['bench', 'dumbbell'],
    difficulty: 'intermediate',
    instructions: ['后脚置于凳上', '下蹲至前腿约90度', '保持躯干直立', '推回起始位'],
    replacementIds: ['lunge', 'goblet_squat'],
    isCustom: false,
  },
  {
    id: 'calf_raise',
    name: '提踵',
    nameEn: 'Calf Raise',
    category: 'isolation',
    muscleGroups: ['calves'],
    equipment: ['none', 'machine', 'dumbbell'],
    difficulty: 'beginner',
    instructions: ['站立于台阶边缘', '脚跟下沉', '踮起至最高点', '缓慢下放'],
    replacementIds: ['seated_calf_raise'],
    isCustom: false,
  },
  {
    id: 'seated_calf_raise',
    name: '坐姿提踵',
    nameEn: 'Seated Calf Raise',
    category: 'isolation',
    muscleGroups: ['calves'],
    equipment: ['machine', 'dumbbell'],
    difficulty: 'beginner',
    instructions: ['坐于器械上', '前脚掌踩踏板', '踮起至最高点', '缓慢下放'],
    replacementIds: ['calf_raise'],
    isCustom: false,
  },
  {
    id: 'face_pull',
    name: '面拉',
    nameEn: 'Face Pull',
    category: 'isolation',
    muscleGroups: ['shoulders', 'traps'],
    equipment: ['cable'],
    difficulty: 'beginner',
    instructions: ['使用绳索把手', '拉向面部两侧', '外旋手臂', '感受后束收缩'],
    replacementIds: ['reverse_fly'],
    isCustom: false,
  },
  {
    id: 'reverse_fly',
    name: '反向飞鸟',
    nameEn: 'Reverse Fly',
    category: 'isolation',
    muscleGroups: ['shoulders', 'traps'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    instructions: ['俯身持哑铃', '手臂微屈', '向两侧展开', '感受后束收缩'],
    replacementIds: ['face_pull'],
    isCustom: false,
  },
  {
    id: 'hip_thrust',
    name: '臀推',
    nameEn: 'Hip Thrust',
    category: 'compound',
    muscleGroups: ['glutes', 'hamstrings'],
    equipment: ['barbell', 'bench'],
    difficulty: 'intermediate',
    instructions: ['上背靠在凳上', '杠铃置于髋部', '臀部发力推起', '顶部夹紧臀部'],
    replacementIds: ['glute_bridge', 'kettlebell_swing'],
    isCustom: false,
  },
  {
    id: 'glute_bridge',
    name: '臀桥',
    nameEn: 'Glute Bridge',
    category: 'compound',
    muscleGroups: ['glutes', 'hamstrings'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: ['仰卧屈膝', '双脚与肩同宽', '臀部发力推起', '顶部夹紧臀部'],
    replacementIds: ['hip_thrust', 'kettlebell_swing'],
    isCustom: false,
  },
  {
    id: 'lateral_raise',
    name: '侧平举',
    nameEn: 'Lateral Raise',
    category: 'isolation',
    muscleGroups: ['shoulders'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    instructions: ['双手各持哑铃于体侧', '手臂微屈', '侧举至肩高', '缓慢下放'],
    replacementIds: ['cable_lateral_raise'],
    isCustom: false,
  },
  {
    id: 'cable_lateral_raise',
    name: '绳索侧平举',
    nameEn: 'Cable Lateral Raise',
    category: 'isolation',
    muscleGroups: ['shoulders'],
    equipment: ['cable'],
    difficulty: 'beginner',
    instructions: ['单手握住低位滑轮把手', '侧举至肩高', '保持持续张力', '缓慢下放'],
    replacementIds: ['lateral_raise'],
    isCustom: false,
  },
  {
    id: 'leg_curl',
    name: '腿弯举',
    nameEn: 'Leg Curl',
    category: 'isolation',
    muscleGroups: ['hamstrings'],
    equipment: ['machine'],
    difficulty: 'beginner',
    instructions: ['俯卧于器械上', '脚跟勾住垫子', '弯举至臀部', '缓慢回放'],
    replacementIds: ['romanian_deadlift', 'nordic_curl'],
    isCustom: false,
  },
  {
    id: 'nordic_curl',
    name: '北欧卷',
    nameEn: 'Nordic Curl',
    category: 'isolation',
    muscleGroups: ['hamstrings'],
    equipment: ['none'],
    difficulty: 'advanced',
    instructions: ['跪姿固定脚踝', '缓慢前倾身体', '用腘绳肌控制下落', '双手撑地后拉回'],
    replacementIds: ['leg_curl', 'romanian_deadlift'],
    isCustom: false,
  },
  {
    id: 'leg_extension',
    name: '腿屈伸',
    nameEn: 'Leg Extension',
    category: 'isolation',
    muscleGroups: ['quads'],
    equipment: ['machine'],
    difficulty: 'beginner',
    instructions: ['坐于器械上', '小腿前侧垫子', '伸直双腿', '缓慢回放'],
    replacementIds: ['goblet_squat', 'bodyweight_squat'],
    isCustom: false,
  },
  {
    id: 'chest_fly',
    name: '哑铃飞鸟',
    nameEn: 'Dumbbell Chest Fly',
    category: 'isolation',
    muscleGroups: ['chest'],
    equipment: ['dumbbell', 'bench'],
    difficulty: 'beginner',
    instructions: ['平躺在凳上', '双手持哑铃于胸部上方', '手臂微屈向两侧展开', '感受胸肌拉伸'],
    replacementIds: ['cable_chest_fly', 'machine_chest_press'],
    isCustom: false,
  },
  {
    id: 'cable_chest_fly',
    name: '绳索夹胸',
    nameEn: 'Cable Chest Fly',
    category: 'isolation',
    muscleGroups: ['chest'],
    equipment: ['cable'],
    difficulty: 'beginner',
    instructions: ['双手握住高位滑轮', '向内夹至双手靠近', '感受胸肌收缩', '缓慢回放'],
    replacementIds: ['chest_fly', 'machine_chest_press'],
    isCustom: false,
  },
  {
    id: 'hanging_leg_raise',
    name: '悬垂举腿',
    nameEn: 'Hanging Leg Raise',
    category: 'isolation',
    muscleGroups: ['core', 'hip_flexors'],
    equipment: ['pull_up_bar'],
    difficulty: 'intermediate',
    instructions: ['双手握住横杆', '悬垂身体', '直腿举至水平', '缓慢下放'],
    replacementIds: ['plank', 'dead_bug'],
    isCustom: false,
  },
];
